stages:
    - test
    - build
    - deploy

analyze:
    stage: test
    image:
        name: ghcr.io/phpstan/phpstan:latest-php8.4
        entrypoint: [ "" ]
    before_script:
        - composer config --global  cache-dir $PWD/.composer
        - composer install --ignore-platform-reqs
    script:
        - phpstan analyse
    rules:
        - exists:
              - "composer.json"
    cache:
        key: "package_$CI_COMMIT_BRANCH"
        paths:
            - .composer

manifest:
    stage: test
    image: alpine:latest
    before_script:
        - apk update
        - apk add libxml2-utils curl
    script:
        - curl --fail-with-body https://raw.githubusercontent.com/simplia/integration/master/assets/manifest.xsd --output /tmp/manifest.xsd
        - xmllint --schema /tmp/manifest.xsd manifest.xml --noout

unit:
    stage: test
    image: thecodingmachine/php:8.4-v5-cli
    artifacts:
        when: always
        reports:
            junit: phpunit-report.xml
    variables:
        PHP_EXTENSION_GD: 1
        PHP_EXTENSION_BCMATH: 1
        PHP_EXTENSION_EXIF: 1
        PHP_EXTENSION_GETTEXT: 1
        PHP_EXTENSION_INTL: 1
    before_script:
        - composer config --global  cache-dir $PWD/.composer
        - composer install
    script:
        - phpunit tests --log-junit phpunit-report.xml

    rules:
        - exists:
              - "tests/**/*"
    cache:
        key: "package_$CI_COMMIT_BRANCH"
        paths:
            - .composer

build:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [ "" ]
    script:
        - echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$REPOSITORY_URL\":\"ecr-login\"}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination "$REPOSITORY_URL/$ECR_REPOSITORY:$CI_COMMIT_SHA"
    only:
        - master

deploy:
    stage: deploy
    image:
        name: amazon/aws-cli
        entrypoint: [ "" ]
    script:
        - aws ssm put-parameter --name "$VERSION_PATH" --value "$CI_COMMIT_SHA" --overwrite --type String
        - aws ssm put-parameter --name "$MANIFEST_PATH" --value "$(cat manifest.xml)" --overwrite --type String
        - curl --fail-with-body --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://git.simplia.cz/api/v4/projects/902/trigger/pipeline
    environment:
        name: production
    only:
        - master
